
CREATE DATABASE DUP_DATA;

USE DUP_DATA;

CREATE TABLE PERSONS(
NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(30) NOT NULL,
STATE CHAR(2) NOT NULL);
 
INSERT INTO Persons(Name, City, [State]) VALUES('John', 'Dallas','TX');
INSERT INTO Persons(Name, City, [State]) VALUES('Mark', 'Seattle','WA');
INSERT INTO Persons(Name, City, [State]) VALUES('Nick', 'Phoenix','AZ');
INSERT INTO Persons(Name, City, [State]) VALUES('Laila', 'San Jose','CA');
INSERT INTO Persons(Name, City, [State]) VALUES('Samantha', 'Tulsa','OK');
INSERT INTO Persons(Name, City, [State]) VALUES('Bella', 'San Antonio','TX');
INSERT INTO Persons(Name, City, [State]) VALUES('John', 'Dallas','TX');
INSERT INTO Persons(Name, City, [State]) VALUES('John', 'Dallas','TX');
INSERT INTO Persons(Name, City, [State]) VALUES('Mark', 'Seattle','WA');
INSERT INTO Persons(Name, City, [State]) VALUES('Nick', 'Tempe','FL');
INSERT INTO Persons(Name, City, [State]) VALUES('John', 'Dallas','TX');

select name,CITY
from PERSONS
group by name,CITY
having count(*)>1


/*REMOVING DUPLICATES IN SQL SERVER */

--Approach 1: /*REMOVING DUPLICATES USING TEMP TABLE*/

SELECT DISTINCT * FROM PERSONS;

SELECT DISTINCT * INTO #TMP FROM PERSONS;

DELETE FROM PERSONS;

INSERT INTO PERSONS
SELECT * FROM #TMP;

SELECT * FROM Persons;

DROP TABLE #TMP;

--Approach 2: 

DELETE FROM PERSONS;

-- RUN THE INSERT SCRIPT AGAIN

WITH PersonCTE as
(
 SELECT *, ROW_NUMBER() OVER( PARTITION BY  NAME,CITY,[STATE] ORDER BY NAME,CITY,[STATE]) RN 
 FROM PERSONS
 )
 DELETE FROM PersonCTE WHERE RN > 1;

 SELECT * FROM Persons;

 --Approach 3: DELETE DUPLICATE RECORDS WITHOUT USING ROW_NUMBER

 DELETE FROM PERSONS;

-- RUN THE INSERT SCRIPT AGAIN

 ALTER TABLE PERSONS ADD IDENT INT IDENTITY;

 SELECT * FROM Persons;

 SELECT NAME,CITY,STATE,MIN(IDENT) ID
 FROM PERSONS
 GROUP BY NAME,CITY,STATE;

 DELETE FROM PERSONS
 WHERE IDENT NOT IN (
 SELECT MIN(IDENT) ID
 FROM PERSONS
 GROUP BY NAME,CITY,STATE);

 --Approach 4: 

DELETE FROM PERSONS;

ALTER TABLE PERSONS DROP COLUMN IDENT;

-- RUN THE INSERT SCRIPT AGAIN

 SELECT %%physloc%% AS PL,* FROM PERSONS;

 SELECT NAME,CITY,STATE,MIN(%%physloc%%) PL
 FROM PERSONS
 GROUP BY NAME,CITY,STATE;

 DELETE FROM PERSONS
 WHERE %%physloc%% NOT IN (
 SELECT MIN(%%physloc%%) PL
 FROM PERSONS
 GROUP BY NAME,CITY,STATE);



